[package]
name = "rustant-film"
version = "0.1.0"
edition = "2021"

[dependencies]
kamadak-exif = "0.6"
image = "0.25"
imageproc = "0.25.0"
rusttype = "0.9.3"
ab_glyph = "0.2.29"
clap = {version = "4.5.23", features = ["derive"]}
pretty_env_logger = "0.5.0"
log = "0.4.22"
